### ISSUE TITLE
Project, Variant filed too small in db

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/TestResultWebApp#12]
Project and Variant field have currently a size of 20 characters.

For the initial need of the WebApp 20 characters was enough, but using e.g. RobotFramework test results the fields are to short.

=> Need to increased to 100 characters.

To be checked if meaningful for other fields, too.

**Comment by ngoan1608** [comment]
Hi Thomas,

This issue has been implemented in PR https://github.com/test-fullautomation/testresultwebapp/pull/17

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
we need here a concept how to handle such project specific changes.
This has e.g. impact when we rebase the BVT WebApp...
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

I think we can do it by maintaining multiple project specific branches.
The common feature can be cherry-picked to all project branches.
The project specific feature is only merged to the appropriate project branch.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
yes, of course we can make branches, but somehow it makes all again more complex.
I started in BIOS already project branches...
Let us discuss this in one of our meetings.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
merged and solved with #17
