### ISSUE TITLE
Widget problems because of long component names

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/TestResultWebApp#13]
* With component names of RobotFramework AIO the graphics are scaled very unfavorable.
* Long component names exceed available widget space.
* Long component names influence the positions of frames: Widgets are cut because of moved frames.
[TestResultWebApp.pdf](https://github.com/test-fullautomation/testresultwebapp/files/10730726/TestResultWebApp.pdf)

**Comment by test-fullautomation** [comment]
There is no way to display long component names. This takes only space for graphics away.
Instead we need a mapping (with our mapping file) of component names to short-names.

**Comment by ngoan1608** [comment]
Hi Thomas,

Shorten name has been used for mapping in configuration.
I think this ticket can be closed now.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Closed. Mapping table is used to aggregate components and to use short names.
