### ISSUE TITLE
Test database dashboard in endless error loop

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/TestResultWebApp#14]
It is not possible to select a version after selecting a variant (variant: QT-009; version expected: apptest-009).

Dasboard keeps on displaying "loading". Sometimes also a flickering error message occurs (seems to appear and disappear in an endless loop).

Test results are written to database by PyTestLog2DB v. 0.1.2
[DashboardErrors.pdf](https://github.com/test-fullautomation/testresultwebapp/files/10732014/DashboardErrors.pdf)

Happens sometimes.

**Comment by HolQue** [comment]
Addendum:

The flickering error message occurs when I use F5 to update the web page _while_ the web page still tries to load the version.

**Comment by ngoan1608** [comment]
Hi Thomas,
Hi Holger,

As our discussion in previous meeting, the issue come from the corrupted data in database due to out of disk capacity (on Feb 10th).
We can move this ticket to next version(s) for track further similar problem.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Disk was full and cause at the same day other issues => ticket closed
