### ISSUE TITLE
dev and rel tag need to be part of version name

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/TestResultWebApp#29]
The version dropdown box shows repeatedly the same version information.

I assume if a dev-tag is created and later a rel-tag with the same version information than it will have the same name as dev/rel information is dropped.

Improvement:
versions shall be called `jobid_<dev/rel>_version`

**Comment by ngoan1608** [comment]
Integrated in RobotFramework AIO 0.13.0
