### ISSUE TITLE
Missing reference in README.rst

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/TestResultWebApp#9]
[WARNING] Reference not found for 'trwebapp' at .../testresultwebapp/README.rst line 1 column 28

**Comment by ngoan1608** [comment]
Hi Holger,

I have checked the reference link on both [README.rst](https://github.com/test-fullautomation/testresultwebapp/blob/develop/README.rst), [README.md](https://github.com/test-fullautomation/testresultwebapp/blob/develop/README.md) files and their previews, it is correct.
I have no idea why that warning message is thrown (by pypandoc ) when running documentation build to convert README.rst to README.md.

Thank you,
Ngoan

**Comment by HolQue** [comment]
Hi Ngoan,

in the entire README document you use the term "TRWebApp" as link: "TRWebApp**_**". Also in the headline (in line 1). This is much too much. There is completely no need to provide a user so much positions to click on such a link to open the repository on GitHub. One single sentence providing the link, is enough. The error message is caused by the fact that this link is part of a headline. It seems that pandoc does not like to have both the headline and a link together in one line. Please make the headline a simple text without using further syntax elements. Then the error message is gone.

**Comment by test-fullautomation** [comment]
Hi Ngoan,
is this issue solved?

Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

I missed the notification of this conversation.
I have updated README files accordingly in PR #11 .

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
merged with #11
